### ISSUE TITLE
Unable to Install on Windows. Due to CGAL I'm thinking

### ISSUE THREAD

**Issue by ghost** [m-jahn/SysbioTreemaps#9] opened 2020-01-04 01:26 UTC
I'm receiving the following error while downloading this package. I have CGAL 5.0 installed and the correct paths set. Not sure why I'm getting this error.

* installing *source* package 'SysbioTreemaps' ...
** libs
C:/RBuildTools/3.5/mingw_64/bin/g++ -m64 -I"C:/PROGRA~1/MICROS~4/RCLIEN~1/R_SERVER/include" -DNDEBUG  -I"C:/Users//Documents/R/win-library/3.4/Rcpp/include"   -I"C:/swarm/workspace/External-R-3.4.3/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_64/bin/g++ -m64 -I"C:/PROGRA~1/MICROS~4/RCLIEN~1/R_SERVER/include" -DNDEBUG  -I"C:/Users/Robbie Janezic/Documents/R/win-library/3.4/Rcpp/include"   -I"C:/swarm/workspace/External-R-3.4.3/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c voronoiDiagram.cpp -o voronoiDiagram.o
voronoiDiagram.cpp:12:27: fatal error: CGAL/MP_Float.h: No such file or directory
 #include <CGAL/MP_Float.h>

**Comment by m-jahn** [comment] 2020-01-06 15:39
Hey,
the error is most likely caused by the missing or wrong link to the CGAL library on windows. I have only tested compilation on Linux. I will look into that. In the meantime, do you have access to a linux (virtual) machine? I don't know how involved fixing compilation on windows is gonna be.

**Comment by m-jahn** [comment] 2020-03-24 19:56
The issue will persist for a while until I (or somebody else?) finds out how to **install and link** the CGAL library during C++ compilation on windows. I don't have access and knowledge for windows installations to fix this. Help is welcome!

**Comment by dickoa** [comment] 2020-06-07 15:34
Hi @m-jahn ,

Your package is interesting, I was working on a package that also need CGAL and built a package to provides CGAL headers. Since CGAL 4, you can use it as header only package. I plan to release the [`cgal4h`](https://gitlab.com/dickoa/cgal4h) package to CRAN soon.

I made some tests and your package works better with CGAL version 4 (I got some errors with the latest version of CGAL i.e version 5).

I made some changes so that it depends on `cgal4h` but you can also just ship the CGAL headers in the inst directory and link to it. The only caveats it's CGAL headers need Boost headers, we can use the `BH` R package but I will see how to remove this dependencies when it's no directly used in CGAL code.
I will send a PR ASAP to show this approach to build your package and btw it also works on Windows.

Best,

**Comment by m-jahn** [comment] 2020-06-08 07:08
This is awesome news! Great you found time to look into that, that really comes as a surprise to me. I'm really not too experienced with C++ and headers, even less when it comes to compilation on Windows. So not having to load the CGAL library and only relying on R/CRAN dependencies would be great. I will test your PR and may get back with some question as to how this works.

**Comment by dickoa** [comment] 2020-06-08 08:54
I'm also learning C++/Rcpp and how to build R package with compiled code and I really hope that it will allow people to easily install your awesome package. Let me know how your tests goes.
Ahmadou

**Comment by m-jahn** [comment] 2020-06-10 11:00
Merged the commit in PR #12 from @dickoa which makes the package now usable without installation of the external CGAL library. All dependencies needed are R dependencies, and all except one are on CRAN (the CGAL header-only library is on https://gitlab.com/dickoa/cgal4h, therefore I close this issue.

**Closed as completed by m-jahn** 2020-06-10 11:00 UTC
Labels: bug, help wanted

**Comment by dickoa** [comment] 2020-06-10 11:02
Thanks for moving forward on this, I didn't have much time the past 2 days to have another look and glad it works. I will do my best to push it to CRAN this or the following one.
Thanks

**Comment by m-jahn** [comment] 2020-06-10 11:09
This issue with CGAL was bugging me all along. I'm really glad you made this contribution. That means I can probably deploy the package on CRAN and most definitely make a Shiny app once I find the time.

**Comment by dickoa** [comment] 2020-06-30 21:08
Good news @m-jahn, the package has been accepted to CRAN
https://cran.r-project.org/package=cgal4h
I would love if you can do some testing to make sure that it works as expected.
Thanks,

**Comment by m-jahn** [comment] 2020-07-01 08:03
That's great news, will do that and get back to you.
