### ISSUE TITLE
Error in install the package

### ISSUE THREAD

**Issue by msgoussi** [m-jahn/SysbioTreemaps#35] opened 2023-10-03 03:30 UTC
Hi...
When i run this code devtools::install_github("m-jahn/WeightedTreemaps"),   I get this error

 devtools::install_github("m-jahn/WeightedTreemaps")
Downloading GitHub repo m-jahn/WeightedTreemaps@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Windows\Temp\Rtmp2xUHqk\remotesef876a23625\m-jahn-WeightedTreemaps-614e114/DESCRIPTION' (773ms)
─  preparing 'WeightedTreemaps': (348ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'WeightedTreemaps_0.1.1.tar.gz'

compilation terminated.
make: *** [C:/ERS_PR~1/R/R-43~1.1/etc/x64/Makeconf:272: voronoiDiagram.o] Error 1
ERROR: compilation failed for package 'WeightedTreemaps'
* removing 'C:/ERS_Programs/R/R-4.3.1/library/WeightedTreemaps'
Warning message:
In i.p(...) :
  installation of package ‘C:/windows/TEMP/Rtmp2xUHqk/fileef82033748f/WeightedTreemaps_0.1.1.tar.gz’ had non-zero exit status

**Comment by m-jahn** [comment] 2023-10-04 06:11
Hey. You seem to be compiling on Windows. I can't reproduce this error because I'm using Linux, however the package builds fine in github actions automatic test even on Windows. The error message is unfortunately not very informative. Can you check that you have the necessary requirements? The package needs a C++ 17 compiler such as `gcc`. Also you might want to check if the required dependencies are correctly installed, such as R packages `bh`, `Rcpp`, and `RcppCGAL` which is currently installed from github instead of CRAN --> see https://github.com/ericdunipace/RcppCGAL
Maybe try to install this particular package separately and see if it builds?

**Comment by m-jahn** [comment] 2023-10-04 06:28
Correction: the package did not install correctly on GH actions on Windows.
See log here: https://github.com/m-jahn/WeightedTreemaps/actions/runs/6143193156/job/16666179017

The package stops building when installing the remote dependency `RcppCGAL`, just as I suspected. I recommend to you installing it manually, and see what happens there. You can paste the error message here if it fails, I'd be curious to see that.

**Comment by m-jahn** [comment] 2023-10-04 11:22
BTW in the mean time you can use a Shiny App to plot your data --> https://m-jahn.shinyapps.io/ShinyTreemaps/

**Comment by msgoussi** [comment] 2023-10-05 03:14
devtools::install("RcppCGAL")
Error in `package_file()`:
! RcppCGAL is not a directory.

**Comment by msgoussi** [comment] 2023-10-05 03:34
Hi I figured it out
after re installing BH, Rcpp, and RcppCGAL.
I ran this code (according to instructions in https://github.com/ericdunipace/RcppCGAL)
library(RcppCGAL) 
Performing one-time download of CGAL from
    https://github.com/CGAL/cgal/releases/download/v5.6/CGAL-5.6.tar.xz

once i loaded the library RcppCGAL, and new folder was created (R\R-4.3.1\library\RcppCGAL\include\CGAL)

Then i run

devtools::install_github("m-jahn/WeightedTreemaps")

i succeeded to install weightedtreemap

**Comment by m-jahn** [comment] 2023-10-05 06:16
great, will close this now.

**Closed as completed by m-jahn** 2023-10-05 06:16 UTC
